openapi: 3.0.1
info:
  title: LibrAPI
  termsOfService: http://swagger.io/terms/
  description: 📚 API Library management system made with SpringBoot. 💳 Phoebus @paystore
    training project in partnership with @ayty-org
  contact:
    email: pedro.sousa@phoebus.com.br
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
  - name: user-controller
    description: Everything about available users
  - name: purchase-controller
    description: Everything about all purchases made
  - name: category-controller
    description: Everything about book categories
  - name: book-controller
    description: Everything about all books
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://librapi.herokuapp.com
  - url: https://localhost:8080
  - url: http://localhost:8080/v2/docs
paths:
  /v1/api/users/{id}:
    get:
      tags:
        - user-controller
      summary: Get an existing user by its ID
      operationId: findByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - user-controller
      operationId: update
      summary: Update an existing user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        204:
          description: No Content
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - user-controller
      operationId: delete
      summary: Delete an existing user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: No Content
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/purchases/{id}:
    get:
      tags:
        - purchase-controller
      operationId: findById
      summary: Get an existing purchase by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
    put:
      tags:
        - purchase-controller
      operationId: update_1
      summary: Update an existing purchase
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseDTO'
        required: true
      responses:
        201:
          description: Created
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - purchase-controller
      operationId: delete_1
      summary: Delete an existing purchase
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: No Content
        201:
          description: Created
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/categories/{id}:
    get:
      tags:
        - category-controller
      operationId: findById_1
      summary: Get an existing category by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - category-controller
      operationId: update_2
      summary: Update an existing category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDTO'
        required: true
      responses:
        204:
          description: No Content
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - category-controller
      operationId: delete_2
      summary: Delete an existing purchase
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: No Content
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/books/{id}:
    get:
      tags:
        - book-controller
      operationId: findById_2
      summary: Get an existing book by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      tags:
        - book-controller
      operationId: update_3
      summary: Update an existing book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDTO'
        required: true
      responses:
        204:
          description: No Content
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      tags:
        - book-controller
      summary: Delete an existing book
      operationId: delete_3
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: No Content
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/users:
    post:
      tags:
        - user-controller
      operationId: save
      summary: Creates a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
        required: true
      responses:
        201:
          description: Created
        404:
          description: Not Found. Id must be higher than 0 or specified user ID doesn't exist
        401:
          description: Unauthorized
        403:
          description: Forbidden
        409:
          description: Conflict. Already exists an user with specified email or phone
  /v1/api/purchases:
    post:
      tags:
        - purchase-controller
      operationId: save_1
      summary: Creates a new purchase
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseDTO'
        required: true
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/categories:
    get:
      tags:
        - category-controller
      operationId: findAll_2
      summary: Gets all categories without pagination
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden

    post:
      tags:
        - category-controller
      summary: Creates a new category
      operationId: save_2
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDTO'
        required: true
      responses:
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/books:
    post:
      tags:
        - book-controller
      operationId: save_3
      summary: Creates a new book
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDTO'
        required: true
      responses:
        201:
          description: Created
        409:
          description: Conflict. Already exists an book with this ISBN
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/users/all:
    get:
      tags:
        - user-controller
      operationId: findAll
      summary: Gets all users without pagination
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/users/:
    get:
      tags:
        - user-controller
      operationId: listPageUser
      summary: Gets all users with pagination
      parameters:
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pageable'
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/purchases/status/{status}:
    get:
      tags:
        - purchase-controller
      operationId: findByStatus
      summary: Gets all purchases by its STATUS
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
            enum:
              - COMPLETED
              - FINISHED
              - CLOSED
              - PENDING
              - DELIVERED
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseDTO'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/purchases/all:
    get:
      tags:
        - purchase-controller
      operationId: findAll_1
      summary: Gets all purchases without pagination
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseDTO'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/purchases/:
    get:
      tags:
        - purchase-controller
      operationId: listPurchases
      summary: Gets all purchases with pagination
      parameters:
        - name: pageable
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pageable'
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/books/category/{categoryName}:
    get:
      tags:
        - book-controller
      operationId: findBookByCategoriesName
      summary: Get all books by CATEGORY name
      parameters:
        - name: categoryName
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /v1/api/books/all:
    get:
      tags:
        - book-controller
      operationId: findAll_3
      summary: Find all books without pagination
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTO'
        401:
          description: Unauthorized
        403:
          description: Forbidden
components:
  schemas:
    UserDTO:
      required:
        - age
        - email
        - name
        - phone
        - sex
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 50
          minLength: 2
          type: string
        age:
          maximum: 2
          minimum: 2
          type: integer
          format: int32
        phone:
          maxLength: 15
          minLength: 8
          type: string
        email:
          type: string
        sex:
          type: string
          enum:
            - MALE
            - FEMALE
            - UNDEFINED
    PurchaseDTO:
      required:
        - amountToPay
        - purchasedBooks
        - status
        - user
      type: object
      properties:
        id:
          type: integer
          format: int64
        user:
          $ref: '#/components/schemas/UserDTO'
        purchasedBooks:
          maxItems: 2147483647
          minItems: 1
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/BookDTO'
        amountToPay:
          minimum: 0
          type: number
          format: double
        status:
          type: string
          enum:
            - COMPLETED
            - FINISHED
            - CLOSED
            - PENDING
            - DELIVERED
    CategoryDTO:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          maxLength: 50
          minLength: 2
          type: string
    BookDTO:
      required:
        - author
        - availableQuantity
        - category
        - isbn
        - publicationYear
        - sellPrice
        - synopsis
        - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        isbn:
          maxLength: 17
          minLength: 17
          type: string
        title:
          maxLength: 50
          minLength: 1
          type: string
        synopsis:
          maxLength: 120
          minLength: 1
          type: string
        author:
          type: string
        publicationYear:
          type: string
          format: date
        sellPrice:
          minimum: 0
          type: number
          format: double
        availableQuantity:
          minimum: 0
          type: integer
          format: int32
        category:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/CategoryDTO'
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
