spring:
    profiles:
        active: dev
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        baseline-on-migrate: false
        enabled: true
        locations: classpath:/db/migration

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        operationsSorter: method