spring:
    profiles:
        active: dev
    jpa:
        properties:
            hibernate:
                schema_update:
                    unique_constraint_strategy: RECREATE_QUIETLY
        hibernate:
            ddl-auto: update
    flyway:
        baseline-on-migrate: false
        enabled: true
        locations: classpath:/db/migration

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        operationsSorter: method

hibernate:
    schema_update:
        unique_constraint_strategy: RECREATE_QUIETLY