CREATE TABLE category( id BIGSERIAL NOT NULL PRIMARY KEY, name VARCHAR NOT NULL);
INSERT INTO category(name) VALUES('Administração, Negócios e Economia');
INSERT INTO category(name) VALUES('Arte, Cinema e Fotografia');
INSERT INTO category(name) VALUES('Artesanato, Casa e Estilo de Vida');
INSERT INTO category(name) VALUES('Autoajuda');
INSERT INTO category(name) VALUES('Biografias');
INSERT INTO category(name) VALUES('Ciências');
INSERT INTO category(name) VALUES('Computação, Informática e Mídias Digitais');
INSERT INTO category(name) VALUES('Crônicas, Humor e Entretenimento');
INSERT INTO category(name) VALUES('Direito');
INSERT INTO category(name) VALUES('Educação');
INSERT INTO category(name) VALUES('Engenharia');
INSERT INTO category(name) VALUES('Esportes e Lazer');
INSERT INTO category(name) VALUES('Fantasia, Horror e Ficção');
INSERT INTO category(name) VALUES('Gastronomia');
INSERT INTO category(name) VALUES('História');
INSERT INTO category(name) VALUES('HQs, Mangás e Graphic Novels');
INSERT INTO category(name) VALUES('Infantil');
INSERT INTO category(name) VALUES('Jovens e Adolescentes');
INSERT INTO category(name) VALUES('Literatura');
INSERT INTO category(name) VALUES('LGBT');
INSERT INTO category(name) VALUES('Medicina');
INSERT INTO category(name) VALUES('Policial, Suspense e Mistério');
INSERT INTO category(name) VALUES('Política, Filosofia e Ciências Sociais');
INSERT INTO category(name) VALUES('Religião e Espiritualidade');
INSERT INTO category(name) VALUES('Romance');
INSERT INTO category(name) VALUES('Saúde e Família');
INSERT INTO category(name) VALUES('Turismo e Guias de Viagem');
INSERT INTO category(name) VALUES('Inglês e Outras Línguas');
